const song = {
    "songLen": 150,
    "songData": [
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 0,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 60,
            "env_attack": 50,
            "env_sustain": 419,
            "env_release": 4607,
            "env_master": 130,
            "fx_filter": 1,
            "fx_freq": 10332,
            "fx_resonance": 120,
            "fx_delay_time": 4,
            "fx_delay_amt": 16,
            "fx_pan_freq": 5,
            "fx_pan_amt": 108,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 5,
            "lfo_amt": 187,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        147,
                        0,
                        0,
                        147,
                        147,
                        0,
                        147,
                        147,
                        0,
                        0,
                        147,
                        0,
                        147,
                        0,
                        147,
                        147,
                        147,
                        0,
                        0,
                        147,
                        147,
                        0,
                        147,
                        147,
                        0,
                        0,
                        147,
                        147,
                        0,
                        147,
                        147,
                        147
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 2,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 18,
            "osc2_xenv": 0,
            "osc2_vol": 255,
            "osc2_waveform": 2,
            "noise_fader": 117,
            "env_attack": 30021,
            "env_sustain": 75047,
            "env_release": 81599,
            "env_master": 192,
            "fx_filter": 2,
            "fx_freq": 200,
            "fx_resonance": 254,
            "fx_delay_time": 8,
            "fx_delay_amt": 72,
            "fx_pan_freq": 2,
            "fx_pan_amt": 142,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                1,
                1,
                2,
                3,
                1,
                1,
                2,
                3,
                1,
                1,
                2,
                3,
                1,
                1,
                2,
                3,
                1,
                1,
                2,
                3,
                1,
                1,
                2,
                3,
                1,
                1,
                2,
                3,
                1,
                1,
                2,
                3,
                1,
                1,
                2,
                3,
                1,
                1,
                2,
                3
            ],
            "c": [
                {
                    "n": [
                        111,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        118,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        114,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        }
    ],
    "rowLen": 5011,
    "endPattern": 41
}